APPLICATION_SERVER_PORT: 8080

DATASOURCE_URL: jdbc:postgresql://localhost:5432/springlearningprofessional
DATASOURCE_USERNAME: root
DATASOURCE_PASSWORD: password
DATASOURCE_DRIVER_CLASSNAME: org.postgresql.Driver

DDL_AUTO: none
DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

FLYWAY_ENABLED: true